### ISSUE TITLE
ModuleNotFoundError: No module named 'importlib_resources'

### ISSUE THREAD

**Issue by zack-emmert** [gumyr/bd_warehouse#20]
After installing according to the installation guide in the documentation, when trying to import from `bd_warehouse.fastener`, I get the error message: `ModuleNotFoundError: No module named 'importlib_resources'`. Here's a more detailed log from the Jupyter notebook:

```
File ~/<Project Path>/.venv/lib/python3.11/site-packages/bd_warehouse/fastener.py:44
     41 from typing import Literal, Optional, Union
     43 import bd_warehouse
---> 44 import importlib_resources
     45 from bd_warehouse.thread import IsoThread, imperial_str_to_float, is_safe
     46 from build123d.build_common import (
     47     IN,
     48     MM,
   (...)
     52     validate_inputs,
     53 )

ModuleNotFoundError: No module named 'importlib_resources'
```

I'm running on fully updated Arch Linux using Python 3.11.8.

**Comment by gumyr** [comment]
`importlib_resources` is a standard Python package and shouldn't have to be installed independently as far as I know.  However, Arch Linux looks like it has it in an 'extra` library - see here: https://archlinux.org/packages/extra/any/python-importlib_resources/ - so I guess it needs to be installed separately on your system.  Not sure what to do about that.

**Comment by fischman** [comment]
FWIW I had an identical experience on Ubuntu 22.04 where `pip install git+https://github.com/gumyr/bd_warehouse` still required a separate `pip install importlib-resources` for `from bd_warehouse.fastener import Screw` to work.

> importlib_resources is a standard Python package

@gumyr: I think you're confusing `importlib.resources`, which is standard for python >= 3.7, with `importlib_resources`, which is "a backport of Python standard library [importlib.resources](https://docs.python.org/3/library/importlib.html#module-importlib.resources) module for older Pythons" (quoting https://pypi.org/project/importlib-resources/). 
(note period vs underscore in package names)

Since bd_warehouse requires [python >= 3.9](https://github.com/gumyr/bd_warehouse/blob/4974217d5f1d394d1337a7974efa593c3d8938d1/pyproject.toml#L20), seems like you could replace bd_warehouse's use of `importlib_resources` with `importlib.resources`.

**Comment by gumyr** [comment]
Fixed.  Thanks for reporting the problem and for the fix.
